using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace pro_compiler
{
    public class SourceTemplate
    {
        public static string Top =
@"using System;

/* AUTOGENERATED BY HACK COMPILER V 0.1 */
namespace Program
{
    public class MainApp
    {             
";

        public static string Bottom =
@"
        }
    }
}
";
        public static string FuncTop =
@"public static dynamic ";            
    }
}
